# Model predykcyjny oparty na regresji liniowej

Celem analizy jest stworzenie modelu umożliwiającego predykcje ceny samochodu w zależności od jego specyfikacji. Lista potemcjalnych regresorów:
* Marka -> bazując na wiedzy rynku samochodowego niektóre marki do co zasady są droższe od innych np. BMW jest droższe od Renault
* Przebieg -> bazując na intuicji, im niższy przebieg, tym droższy samochód powinien być
* Moc silnika -> droższe samochody powinny mieć mocniejszy silnik
* Rocznik -> poza outlierami im starsze auto tym tańsze powinno być

## Przygotowanie danych

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
sns.set_theme(style="whitegrid")

In [13]:
data = pd.read_csv('cars_data.csv')
data

              Marka  ... Pojemność silnika
0        Alfa Romeo  ...               NaN
1             Volvo  ...               NaN
2              Ford  ...               NaN
3            Jaguar  ...               NaN
4             Cupra  ...               2.0
...             ...  ...               ...
9652  SsangYong/KGM  ...               NaN
9653  Mercedes-Benz  ...               NaN
9654     Land Rover  ...               NaN
9655     Volkswagen  ...               1.5
9656     Alfa Romeo  ...               NaN

[9657 rows x 9 columns]

In [14]:
data.describe(include='all')

       Marka       Model  ...  Skrzynia biegów Pojemność silnika
count   9657        9657  ...             9657       4139.000000
unique    94        5630  ...                2               NaN
top      BMW  Opel Astra  ...         Manualna               NaN
freq     725          58  ...             4838               NaN
mean     NaN         NaN  ...              NaN          1.669896
std      NaN         NaN  ...              NaN          0.517889
min      NaN         NaN  ...              NaN          1.000000
25%      NaN         NaN  ...              NaN          1.400000
50%      NaN         NaN  ...              NaN          1.600000
75%      NaN         NaN  ...              NaN          2.000000
max      NaN         NaN  ...              NaN          5.700000

[11 rows x 9 columns]

In [15]:
data.isnull().sum()

Marka                   0
Model                   0
Cena                    0
Waluta                  0
Paliwo                  0
Przebieg                0
Rocznik                 0
Skrzynia biegów         0
Pojemność silnika    5518
dtype: int64

## Feature engineering zmiennej Pojemność silnika

Jako że 57% danych w tej kolumnie numerycznej stanowią braki, zastosowane zostanie dwustopniowe podejście:
1. Utworzenie kolumny pomocniczej: Pojemność znana
2. Imputacja braków za pomocą mediany grupy + zachowanie zmiennej

In [16]:
df = pd.read_csv("cars_data.csv")

# Sprawdźmy, czy dla brakujących wierszy możemy odtworzyć pojemność z innych aut tej samej marki i modelu
# (jeśli dany model ma w bazie wersje z znaną pojemnością)
print("Liczba unikalnych modeli z brakami:", df[df['Pojemność silnika'].isnull()]['Model'].nunique())

Liczba unikalnych modeli z brakami: 2381